import type { Workflow } from "@embedflow/workflow-engine";
import { getActivity } from "@embedflow/activity-registry";

// --- Types ---

export type TargetPlatform = "arduino-uno" | "arduino-nano" | "arduino-mega" | "esp32" | "esp8266";

export interface CodegenOptions {
  target: TargetPlatform;
  comments: boolean;
  language: "fr" | "en";
}

export interface CodegenResult {
  code: string;
  includes: string[];
  libraries: { name: string; version: string }[];
  estimatedRam: number;
  estimatedFlash: number;
}

// --- RAM/Flash estimates per library ---
const LIBRARY_COSTS: Record<string, { ram: number; flash: number }> = {
  "DHT.h": { ram: 32, flash: 1200 },
  "Servo.h": { ram: 60, flash: 1000 },
  "LiquidCrystal_I2C.h": { ram: 80, flash: 1500 },
  "Adafruit_SSD1306.h": { ram: 1024, flash: 8000 },
  "Adafruit_NeoPixel.h": { ram: 40, flash: 2000 },
  "WiFi.h": { ram: 2048, flash: 12000 },
  "HTTPClient.h": { ram: 512, flash: 4000 },
  "DallasTemperature.h": { ram: 64, flash: 2000 },
  "Adafruit_BMP280.h": { ram: 128, flash: 4000 },
};

// --- Topological sort ---
function topoSort(workflow: Workflow): string[] {
  const inDegree = new Map<string, number>();
  const adj = new Map<string, string[]>();
  for (const node of workflow.nodes) {
    inDegree.set(node.id, 0);
    adj.set(node.id, []);
  }
  for (const edge of workflow.edges) {
    adj.get(edge.sourceNodeId)?.push(edge.targetNodeId);
    inDegree.set(edge.targetNodeId, (inDegree.get(edge.targetNodeId) || 0) + 1);
  }
  const queue = workflow.nodes.filter((n) => (inDegree.get(n.id) || 0) === 0).map((n) => n.id);
  const order: string[] = [];
  while (queue.length > 0) {
    const id = queue.shift()!;
    order.push(id);
    for (const next of adj.get(id) || []) {
      const deg = (inDegree.get(next) || 1) - 1;
      inDegree.set(next, deg);
      if (deg === 0) queue.push(next);
    }
  }
  // Add any remaining nodes (cycles or disconnected)
  for (const node of workflow.nodes) {
    if (!order.includes(node.id)) order.push(node.id);
  }
  return order;
}

// --- Code generation ---

export function generateCode(
  workflow: Workflow,
  options: CodegenOptions = { target: "arduino-uno", comments: true, language: "fr" },
): CodegenResult {
  const allIncludes = new Set<string>();
  const allLibraries = new Map<string, string>();
  const globalFragments: string[] = [];
  const setupFragments: string[] = [];
  const loopFragments: string[] = [];

  // Track globals to deduplicate instances (same sensor on same pin)
  const seenGlobals = new Set<string>();

  // Process nodes in topological order
  const sortedIds = topoSort(workflow);
  const nodeMap = new Map(workflow.nodes.map((n) => [n.id, n]));

  for (const nodeId of sortedIds) {
    const node = nodeMap.get(nodeId);
    if (!node) continue;

    const activity = getActivity(node.activityId);
    if (!activity) continue;

    // Collect includes (Set deduplicates automatically)
    for (const inc of activity.codegen.includes) {
      allIncludes.add(inc);
    }
    for (const lib of activity.codegen.libraries) {
      allLibraries.set(lib.name, lib.version);
    }

    const props = node.properties;

    // Globals — deduplicate identical declarations (instance sharing)
    const globalsCode = activity.codegen.globals(props);
    if (globalsCode && !seenGlobals.has(globalsCode)) {
      seenGlobals.add(globalsCode);
      globalFragments.push(globalsCode);
    }

    // Setup
    const setupCode = activity.codegen.setup(props);
    if (setupCode && !seenGlobals.has("setup:" + setupCode)) {
      seenGlobals.add("setup:" + setupCode);
      setupFragments.push(setupCode);
    }

    // Loop — always include, with a comment identifying the block
    const loopCode = activity.codegen.loop(props, {}, {});
    if (loopCode) {
      if (options.comments) {
        loopFragments.push(`// ${activity.label}`);
      }
      loopFragments.push(loopCode);
      loopFragments.push(""); // blank line between blocks
    }
  }

  // --- Assemble final code ---
  const lines: string[] = [];

  // Header comment
  if (options.comments) {
    const isFr = options.language === "fr";
    lines.push(
      `// ${isFr ? "Genere par EmbedFlow" : "Generated by EmbedFlow"}`,
      `// ${isFr ? "Projet" : "Project"} : ${workflow.name}`,
      `// ${isFr ? "Carte" : "Board"} : ${options.target}`,
      `// ${isFr ? "Date" : "Date"} : ${new Date().toLocaleDateString(options.language)}`,
      "",
    );
  }

  // Includes
  if (allIncludes.size > 0) {
    if (options.comments) lines.push("// --- Includes ---");
    for (const inc of allIncludes) {
      lines.push(`#include <${inc}>`);
    }
    lines.push("");
  }

  // Globals
  if (globalFragments.length > 0) {
    if (options.comments) lines.push("// --- Variables globales ---");
    lines.push(...globalFragments, "");
  }

  // setup()
  if (options.comments) lines.push("// --- Initialisation ---");
  lines.push("void setup() {");
  if (setupFragments.length > 0) {
    lines.push(...setupFragments.map((s) => "  " + s.split("\n").join("\n  ")));
  } else {
    lines.push("  // Rien a initialiser");
  }
  lines.push("}", "");

  // loop()
  if (options.comments) lines.push("// --- Boucle principale ---");
  lines.push("void loop() {");
  if (loopFragments.length > 0) {
    lines.push(...loopFragments.map((s) => (s === "" ? "" : "  " + s.split("\n").join("\n  "))));
  } else {
    lines.push("  // Aucune action");
  }
  lines.push("}", "");

  // --- Estimate RAM/Flash ---
  let estimatedRam = 200; // Arduino runtime base
  let estimatedFlash = 500;

  for (const inc of allIncludes) {
    const cost = LIBRARY_COSTS[inc];
    if (cost) {
      estimatedRam += cost.ram;
      estimatedFlash += cost.flash;
    }
  }
  estimatedRam += globalFragments.length * 20;
  estimatedFlash += (setupFragments.length + loopFragments.length) * 50;

  return {
    code: lines.join("\n"),
    includes: Array.from(allIncludes),
    libraries: Array.from(allLibraries.entries()).map(([name, version]) => ({ name, version })),
    estimatedRam,
    estimatedFlash,
  };
}
