import type { Workflow } from "@embedflow/workflow-engine";
import { getActivity } from "@embedflow/activity-registry";

// --- Types ---

export type TargetPlatform = "arduino-uno" | "arduino-nano" | "arduino-mega" | "esp32" | "esp8266";

export interface CodegenOptions {
  target: TargetPlatform;
  comments: boolean;
  language: "fr" | "en";
}

export interface CodegenResult {
  code: string;
  includes: string[];
  libraries: { name: string; version: string }[];
  estimatedRam: number;
  estimatedFlash: number;
}

// --- Code generation ---

export function generateCode(
  workflow: Workflow,
  options: CodegenOptions = { target: "arduino-uno", comments: true, language: "fr" },
): CodegenResult {
  const allIncludes = new Set<string>();
  const allLibraries = new Map<string, string>();
  const globalFragments: string[] = [];
  const setupFragments: string[] = [];
  const loopFragments: string[] = [];

  for (const node of workflow.nodes) {
    const activity = getActivity(node.activityId);
    if (!activity) continue;

    for (const inc of activity.codegen.includes) {
      allIncludes.add(inc);
    }
    for (const lib of activity.codegen.libraries) {
      allLibraries.set(lib.name, lib.version);
    }

    const props = node.properties;
    const globalsCode = activity.codegen.globals(props);
    if (globalsCode) globalFragments.push(globalsCode);

    const setupCode = activity.codegen.setup(props);
    if (setupCode) setupFragments.push(setupCode);

    const loopCode = activity.codegen.loop(props, {}, {});
    if (loopCode) loopFragments.push(loopCode);
  }

  const commentPrefix = options.comments
    ? options.language === "fr"
      ? "// Généré par EmbedFlow\n// Carte : " + options.target + "\n\n"
      : "// Generated by EmbedFlow\n// Board: " + options.target + "\n\n"
    : "";

  const includesSection = Array.from(allIncludes)
    .map((inc) => `#include <${inc}>`)
    .join("\n");

  const code = [
    commentPrefix,
    includesSection,
    "",
    globalFragments.join("\n"),
    "",
    "void setup() {",
    setupFragments.map((s) => "  " + s).join("\n") || "  // Initialisation",
    "}",
    "",
    "void loop() {",
    loopFragments.map((s) => "  " + s).join("\n") || "  // Boucle principale",
    "}",
    "",
  ].join("\n");

  return {
    code,
    includes: Array.from(allIncludes),
    libraries: Array.from(allLibraries.entries()).map(([name, version]) => ({ name, version })),
    estimatedRam: 0,
    estimatedFlash: 0,
  };
}
