import type { Workflow, WorkflowArgument } from "@embedflow/workflow-engine";
import { getActivity } from "@embedflow/activity-registry";

// --- Types ---

export type TargetPlatform = "arduino-uno" | "arduino-nano" | "arduino-mega" | "esp32" | "esp8266";

export interface CodegenOptions {
  target: TargetPlatform;
  comments: boolean;
  language: "fr" | "en";
}

export interface CodegenResult {
  code: string;
  includes: string[];
  libraries: { name: string; version: string }[];
  estimatedRam: number;
  estimatedFlash: number;
}

// --- RAM/Flash estimates per library ---
const LIBRARY_COSTS: Record<string, { ram: number; flash: number }> = {
  "DHT.h": { ram: 32, flash: 1200 },
  "Servo.h": { ram: 60, flash: 1000 },
  "LiquidCrystal_I2C.h": { ram: 80, flash: 1500 },
  "Adafruit_SSD1306.h": { ram: 1024, flash: 8000 },
  "Adafruit_NeoPixel.h": { ram: 40, flash: 2000 },
  "WiFi.h": { ram: 2048, flash: 12000 },
  "HTTPClient.h": { ram: 512, flash: 4000 },
  "DallasTemperature.h": { ram: 64, flash: 2000 },
  "Adafruit_BMP280.h": { ram: 128, flash: 4000 },
};

// --- Topological sort ---
function topoSort(workflow: Workflow): string[] {
  const inDegree = new Map<string, number>();
  const adj = new Map<string, string[]>();
  for (const node of workflow.nodes) {
    inDegree.set(node.id, 0);
    adj.set(node.id, []);
  }
  for (const edge of workflow.edges) {
    adj.get(edge.sourceNodeId)?.push(edge.targetNodeId);
    inDegree.set(edge.targetNodeId, (inDegree.get(edge.targetNodeId) || 0) + 1);
  }
  const queue = workflow.nodes.filter((n) => (inDegree.get(n.id) || 0) === 0).map((n) => n.id);
  const order: string[] = [];
  while (queue.length > 0) {
    const id = queue.shift()!;
    order.push(id);
    for (const next of adj.get(id) || []) {
      const deg = (inDegree.get(next) || 1) - 1;
      inDegree.set(next, deg);
      if (deg === 0) queue.push(next);
    }
  }
  // Add any remaining nodes (cycles or disconnected)
  for (const node of workflow.nodes) {
    if (!order.includes(node.id)) order.push(node.id);
  }
  return order;
}

// --- Code generation ---

export function generateCode(
  workflow: Workflow,
  options: CodegenOptions = { target: "arduino-uno", comments: true, language: "fr" },
): CodegenResult {
  const allIncludes = new Set<string>();
  const allLibraries = new Map<string, string>();
  const globalFragments: string[] = [];
  const setupFragments: string[] = [];
  const loopFragments: string[] = [];

  // Track globals to deduplicate instances (same sensor on same pin)
  const seenGlobals = new Set<string>();

  // Process nodes in topological order
  const sortedIds = topoSort(workflow);
  const nodeMap = new Map(workflow.nodes.map((n) => [n.id, n]));

  for (const nodeId of sortedIds) {
    const node = nodeMap.get(nodeId);
    if (!node) continue;

    const activity = getActivity(node.activityId);
    if (!activity) continue;

    const props = node.properties;
    const ctx = { nodeId };

    // Collect includes (Set deduplicates automatically)
    const resolvedIncludes =
      typeof activity.codegen.includes === "function"
        ? activity.codegen.includes(props)
        : activity.codegen.includes;
    for (const inc of resolvedIncludes) {
      allIncludes.add(inc);
    }

    // Collect libraries
    const resolvedLibraries =
      typeof activity.codegen.libraries === "function"
        ? activity.codegen.libraries(props)
        : activity.codegen.libraries;
    for (const lib of resolvedLibraries) {
      allLibraries.set(lib.name, lib.version);
    }

    // Globals — deduplicate identical declarations (instance sharing)
    const globalsCode = activity.codegen.globals(props, ctx);
    if (globalsCode && !seenGlobals.has(globalsCode)) {
      seenGlobals.add(globalsCode);
      globalFragments.push(globalsCode);
    }

    // Setup
    const setupCode = activity.codegen.setup(props, ctx);
    if (setupCode && !seenGlobals.has("setup:" + setupCode)) {
      seenGlobals.add("setup:" + setupCode);
      setupFragments.push(setupCode);
    }

    // Loop — always include, with a comment identifying the block
    const loopCode = activity.codegen.loop(props, {}, {}, ctx);
    if (loopCode) {
      if (options.comments) {
        loopFragments.push(`// ${activity.label}`);
      }
      loopFragments.push(loopCode);
      loopFragments.push(""); // blank line between blocks
    }
  }

  // --- Assemble final code ---
  const lines: string[] = [];

  // Header comment
  if (options.comments) {
    const isFr = options.language === "fr";
    lines.push(
      `// ${isFr ? "Genere par EmbedFlow" : "Generated by EmbedFlow"}`,
      `// ${isFr ? "Projet" : "Project"} : ${workflow.name}`,
      `// ${isFr ? "Carte" : "Board"} : ${options.target}`,
      `// ${isFr ? "Date" : "Date"} : ${new Date().toLocaleDateString(options.language)}`,
      "",
    );
  }

  // Includes
  if (allIncludes.size > 0) {
    if (options.comments) lines.push("// --- Includes ---");
    for (const inc of allIncludes) {
      lines.push(`#include <${inc}>`);
    }
    lines.push("");
  }

  // Globals
  if (globalFragments.length > 0) {
    if (options.comments) lines.push("// --- Variables globales ---");
    lines.push(...globalFragments, "");
  }

  // setup()
  if (options.comments) lines.push("// --- Initialisation ---");
  lines.push("void setup() {");
  if (setupFragments.length > 0) {
    lines.push(...setupFragments.map((s) => "  " + s.split("\n").join("\n  ")));
  } else {
    lines.push("  // Rien a initialiser");
  }
  lines.push("}", "");

  // loop()
  if (options.comments) lines.push("// --- Boucle principale ---");
  lines.push("void loop() {");
  if (loopFragments.length > 0) {
    lines.push(...loopFragments.map((s) => (s === "" ? "" : "  " + s.split("\n").join("\n  "))));
  } else {
    lines.push("  // Aucune action");
  }
  lines.push("}", "");

  // --- Estimate RAM/Flash ---
  let estimatedRam = 200; // Arduino runtime base
  let estimatedFlash = 500;

  for (const inc of allIncludes) {
    const cost = LIBRARY_COSTS[inc];
    if (cost) {
      estimatedRam += cost.ram;
      estimatedFlash += cost.flash;
    }
  }
  estimatedRam += globalFragments.length * 20;
  estimatedFlash += (setupFragments.length + loopFragments.length) * 50;

  return {
    code: lines.join("\n"),
    includes: Array.from(allIncludes),
    libraries: Array.from(allLibraries.entries()).map(([name, version]) => ({ name, version })),
    estimatedRam,
    estimatedFlash,
  };
}

// --- Multi-workflow (project) code generation ---

/**
 * Sanitize a workflow name into a valid C function name.
 * Removes accents, replaces spaces with underscores, adds wf_ prefix.
 */
function sanitizeFunctionName(name: string): string {
  return "wf_" + name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")  // Remove accents
    .replace(/[^a-zA-Z0-9_]/g, "_")   // Replace non-alphanum with _
    .replace(/_+/g, "_")               // Collapse multiple underscores
    .replace(/^_|_$/g, "")             // Trim leading/trailing _
    .toLowerCase();
}

/**
 * Map a WorkflowArgument type to a C type string.
 */
function argToCType(arg: WorkflowArgument): string {
  switch (arg.type) {
    case "number": return "float";
    case "boolean": return "bool";
    case "string": return "const char*";
    default: return "int";
  }
}

/**
 * Generate C code for an entire project with multiple workflows.
 * Sub-workflows become C functions; workflow.invoke nodes become function calls.
 */
export function generateProjectCode(
  workflows: Workflow[],
  options: CodegenOptions = { target: "arduino-uno", comments: true, language: "fr" },
): CodegenResult {
  const mainWorkflow = workflows.find((w) => w.isMain);
  const subWorkflows = workflows.filter((w) => !w.isMain);

  // If no sub-workflows or no main, fall back to single-workflow codegen
  if (!mainWorkflow || subWorkflows.length === 0) {
    return generateCode(mainWorkflow || workflows[0], options);
  }

  // Build a map of workflow ID -> function name
  const fnNames = new Map<string, string>();
  for (const sw of subWorkflows) {
    fnNames.set(sw.id, sanitizeFunctionName(sw.name));
  }

  // Collect all includes, libraries, globals, etc. from ALL workflows
  const allIncludes = new Set<string>();
  const allLibraries = new Map<string, string>();
  const globalFragments: string[] = [];
  const seenGlobals = new Set<string>();

  // Process sub-workflows and generate function bodies
  const functionDeclarations: string[] = [];
  const functionDefinitions: string[] = [];

  for (const sw of subWorkflows) {
    const fnName = fnNames.get(sw.id)!;
    const args = sw.arguments || [];

    // Build parameter list
    const params: string[] = [];
    for (const arg of args) {
      if (arg.direction === "in") {
        params.push(`${argToCType(arg)} ${arg.name}`);
      } else if (arg.direction === "out") {
        params.push(`${argToCType(arg)}* ${arg.name}`);
      } else if (arg.direction === "in_out") {
        params.push(`${argToCType(arg)}* ${arg.name}`);
      }
    }

    const paramStr = params.join(", ");

    // Generate the body of the sub-workflow function
    const subSetupFragments: string[] = [];
    const subLoopFragments: string[] = [];

    const sortedIds = topoSort(sw);
    const nodeMap = new Map(sw.nodes.map((n) => [n.id, n]));

    for (const nodeId of sortedIds) {
      const node = nodeMap.get(nodeId);
      if (!node) continue;

      const activity = getActivity(node.activityId);
      if (!activity) continue;

      const props = node.properties;
      const ctx = { nodeId };

      // Includes
      const resolvedIncludes =
        typeof activity.codegen.includes === "function"
          ? activity.codegen.includes(props)
          : activity.codegen.includes;
      for (const inc of resolvedIncludes) allIncludes.add(inc);

      // Libraries
      const resolvedLibraries =
        typeof activity.codegen.libraries === "function"
          ? activity.codegen.libraries(props)
          : activity.codegen.libraries;
      for (const lib of resolvedLibraries) allLibraries.set(lib.name, lib.version);

      // Globals (top-level, shared)
      const globalsCode = activity.codegen.globals(props, ctx);
      if (globalsCode && !seenGlobals.has(globalsCode)) {
        seenGlobals.add(globalsCode);
        globalFragments.push(globalsCode);
      }

      // Setup
      const setupCode = activity.codegen.setup(props, ctx);
      if (setupCode && !seenGlobals.has("setup:" + setupCode)) {
        seenGlobals.add("setup:" + setupCode);
        subSetupFragments.push(setupCode);
      }

      // Loop
      const loopCode = activity.codegen.loop(props, {}, {}, ctx);
      if (loopCode) {
        if (options.comments) subLoopFragments.push(`  // ${activity.label}`);
        subLoopFragments.push("  " + loopCode.split("\n").join("\n  "));
        subLoopFragments.push("");
      }
    }

    // Forward declaration
    functionDeclarations.push(`void ${fnName}(${paramStr});`);

    // Full definition
    const bodyLines: string[] = [];
    bodyLines.push(`void ${fnName}(${paramStr}) {`);
    if (subLoopFragments.length > 0) {
      bodyLines.push(...subLoopFragments);
    } else {
      bodyLines.push("  // Aucune action");
    }
    bodyLines.push("}");

    functionDefinitions.push(bodyLines.join("\n"));

    // Track sub-workflow setup fragments to add to main setup()
    // (They need to be initialized once in setup)
    for (const s of subSetupFragments) {
      if (!seenGlobals.has("mainsetup:" + s)) {
        seenGlobals.add("mainsetup:" + s);
      }
    }
  }

  // Process main workflow
  const mainSetupFragments: string[] = [];
  const mainLoopFragments: string[] = [];

  const sortedMainIds = topoSort(mainWorkflow);
  const mainNodeMap = new Map(mainWorkflow.nodes.map((n) => [n.id, n]));

  for (const nodeId of sortedMainIds) {
    const node = mainNodeMap.get(nodeId);
    if (!node) continue;

    // Handle workflow.invoke specially
    if (node.activityId === "workflow.invoke") {
      const targetId = node.properties.targetWorkflowId as string;
      const fnName = fnNames.get(targetId);
      const targetWf = subWorkflows.find((w) => w.id === targetId);

      if (fnName && targetWf) {
        const args = targetWf.arguments || [];
        const callArgs: string[] = [];

        // For out/in_out params, declare local variables and pass by pointer
        const preLines: string[] = [];
        const postLines: string[] = [];

        for (const arg of args) {
          if (arg.direction === "in") {
            // Pass value directly (use default or 0)
            const defaultVal = arg.defaultValue ?? (arg.type === "number" ? 0 : arg.type === "boolean" ? "false" : '""');
            callArgs.push(String(defaultVal));
          } else if (arg.direction === "out") {
            const cType = argToCType(arg);
            const defaultVal = arg.type === "number" ? "0" : arg.type === "boolean" ? "false" : '""';
            preLines.push(`${cType} ${arg.name} = ${defaultVal};`);
            callArgs.push(`&${arg.name}`);
          } else if (arg.direction === "in_out") {
            const cType = argToCType(arg);
            const defaultVal = arg.defaultValue ?? (arg.type === "number" ? 0 : arg.type === "boolean" ? "false" : '""');
            preLines.push(`${cType} ${arg.name} = ${defaultVal};`);
            callArgs.push(`&${arg.name}`);
          }
        }

        if (options.comments) {
          mainLoopFragments.push(`// Appel: ${targetWf.name}`);
        }
        for (const line of preLines) mainLoopFragments.push(line);
        mainLoopFragments.push(`${fnName}(${callArgs.join(", ")});`);
        mainLoopFragments.push("");
      }
      continue;
    }

    const activity = getActivity(node.activityId);
    if (!activity) continue;

    const props = node.properties;
    const ctx = { nodeId };

    // Includes
    const resolvedIncludes =
      typeof activity.codegen.includes === "function"
        ? activity.codegen.includes(props)
        : activity.codegen.includes;
    for (const inc of resolvedIncludes) allIncludes.add(inc);

    // Libraries
    const resolvedLibraries =
      typeof activity.codegen.libraries === "function"
        ? activity.codegen.libraries(props)
        : activity.codegen.libraries;
    for (const lib of resolvedLibraries) allLibraries.set(lib.name, lib.version);

    // Globals
    const globalsCode = activity.codegen.globals(props, ctx);
    if (globalsCode && !seenGlobals.has(globalsCode)) {
      seenGlobals.add(globalsCode);
      globalFragments.push(globalsCode);
    }

    // Setup
    const setupCode = activity.codegen.setup(props, ctx);
    if (setupCode && !seenGlobals.has("setup:" + setupCode)) {
      seenGlobals.add("setup:" + setupCode);
      mainSetupFragments.push(setupCode);
    }

    // Loop
    const loopCode = activity.codegen.loop(props, {}, {}, ctx);
    if (loopCode) {
      if (options.comments) mainLoopFragments.push(`// ${activity.label}`);
      mainLoopFragments.push(loopCode);
      mainLoopFragments.push("");
    }
  }

  // --- Assemble final code ---
  const lines: string[] = [];

  // Header
  if (options.comments) {
    const isFr = options.language === "fr";
    lines.push(
      `// ${isFr ? "Genere par EmbedFlow" : "Generated by EmbedFlow"}`,
      `// ${isFr ? "Projet" : "Project"} : ${mainWorkflow.name}`,
      `// ${isFr ? "Carte" : "Board"} : ${options.target}`,
      `// ${isFr ? "Date" : "Date"} : ${new Date().toLocaleDateString(options.language)}`,
      `// ${isFr ? "Sous-workflows" : "Sub-workflows"} : ${subWorkflows.map((w) => w.name).join(", ")}`,
      "",
    );
  }

  // Includes
  if (allIncludes.size > 0) {
    if (options.comments) lines.push("// --- Includes ---");
    for (const inc of allIncludes) lines.push(`#include <${inc}>`);
    lines.push("");
  }

  // Globals
  if (globalFragments.length > 0) {
    if (options.comments) lines.push("// --- Variables globales ---");
    lines.push(...globalFragments, "");
  }

  // Forward declarations
  if (functionDeclarations.length > 0) {
    if (options.comments) lines.push("// --- Declarations des sous-workflows ---");
    lines.push(...functionDeclarations, "");
  }

  // setup()
  if (options.comments) lines.push("// --- Initialisation ---");
  lines.push("void setup() {");
  if (mainSetupFragments.length > 0) {
    lines.push(...mainSetupFragments.map((s) => "  " + s.split("\n").join("\n  ")));
  } else {
    lines.push("  // Rien a initialiser");
  }
  lines.push("}", "");

  // loop()
  if (options.comments) lines.push("// --- Boucle principale ---");
  lines.push("void loop() {");
  if (mainLoopFragments.length > 0) {
    lines.push(...mainLoopFragments.map((s) => (s === "" ? "" : "  " + s.split("\n").join("\n  "))));
  } else {
    lines.push("  // Aucune action");
  }
  lines.push("}", "");

  // Sub-workflow function definitions
  if (functionDefinitions.length > 0) {
    if (options.comments) lines.push("// --- Sous-workflows ---");
    lines.push("");
    for (const def of functionDefinitions) {
      lines.push(def, "");
    }
  }

  // Estimate RAM/Flash
  let estimatedRam = 200;
  let estimatedFlash = 500;
  for (const inc of allIncludes) {
    const cost = LIBRARY_COSTS[inc];
    if (cost) {
      estimatedRam += cost.ram;
      estimatedFlash += cost.flash;
    }
  }
  estimatedRam += globalFragments.length * 20;
  estimatedFlash += (mainSetupFragments.length + mainLoopFragments.length + functionDefinitions.length * 10) * 50;

  return {
    code: lines.join("\n"),
    includes: Array.from(allIncludes),
    libraries: Array.from(allLibraries.entries()).map(([name, version]) => ({ name, version })),
    estimatedRam,
    estimatedFlash,
  };
}
